/* bsp.c — board/SoC bring-up for NXP S32K344 (Cortex-M7) via RTD (Real-Time Drivers).
 *
 * S32K344 = dual Cortex-M7 in lockstep (one logical safety core). Unlike the AURIX
 * multicore AMP, the tri-partition (safety/control/QM) collapses onto this single
 * lockstep core — keep the task-priority separation + MPU partitioning, one scheduler.
 *
 * The Cortex-M FreeRTOS port owns SysTick (tick), PendSV (context switch) and SVC, so
 * there is NO timer-tick ISR here (contrast the AURIX STM version). This BSP does:
 * clock (Clock_Ip), watchdog handling (Swt_Ip / external FS26 SBC), a DWT cycle counter
 * for run-time stats, and leaves interrupts enabled for the NVIC.
 *
 * RTD note: Clock_Ip_aClockConfig / config symbols are produced by S32 Config Tools
 * (EB tresos). Names below match the typical generated output — align to your project.
 */
#include "bsp.h"

/* generated by S32 Config Tools */
extern const Clock_Ip_ClockConfigType  Clock_Ip_aClockConfig[];

Bsp_Init_StatusType Bsp_Init(void)
{
	/* Initialize Clocks */
	Clock_Ip_StatusType Status_Init_Clock = CLOCK_IP_ERROR;
	Status_Init_Clock = Clock_Ip_Init(Clock_Ip_aClockConfig);
	if (Status_Init_Clock != CLOCK_IP_SUCCESS)
	{
		return BSP_INIT_ERROR;
	}

	/* Initialize all pins using Port driver */
	Siul2_Port_Ip_PortStatusType Status_Init_Port = SIUL2_PORT_ERROR;
	Status_Init_Port = Siul2_Port_Ip_Init(NUM_OF_CONFIGURED_PINS_PortContainer_0_BOARD_InitPeripherals, g_pin_mux_InitConfigArr_PortContainer_0_BOARD_InitPeripherals);
	if(Status_Init_Port !=  SIUL2_PORT_SUCCESS)
	{
		return BSP_INIT_ERROR;
	}

	/* Initialize Interrupt */
	IntCtrl_Ip_StatusType Status_Init_Irq = INTCTRL_IP_STATUS_ERROR;
	Status_Init_Irq = IntCtrl_Ip_Init(&IntCtrlConfig_0);
	if (Status_Init_Irq != INTCTRL_IP_STATUS_SUCCESS)
	{
		return BSP_INIT_ERROR;
	}

	/* Initialize LPUART6 */
	Lpuart_Uart_Ip_Init(UART_INSTANCE, &Lpuart_Uart_Ip_xHwConfigPB_6);

	/* Initialize FlexCAN driver */
	FlexCAN_Ip_Init(INST_FLEXCAN_0, &FlexCAN_State0, &FlexCAN_Config0);

	/* Set Rx filter mask type */
	FlexCAN_Ip_SetRxMaskType(INST_FLEXCAN_0, FLEXCAN_RX_MASK_INDIVIDUAL);

	/* Set Rx individual mask value */
	/* Expect to receive all IDs, mask = 0x0 */
	FlexCAN_Ip_SetRxIndividualMask(INST_FLEXCAN_0, RX_MB_IDX, 0x0U);

	/* Start FlexCAN controller */
	FlexCAN_Ip_SetStartMode(INST_FLEXCAN_0);

	/* Initialize transceiver CAN0_STB = 1 & CAN0_EN = 1*/
	Siul2_Dio_Ip_WritePin(CAN0_STB_PORT, CAN0_STB_PIN, 1U);
	Siul2_Dio_Ip_WritePin(CAN0_EN_PORT, CAN0_EN_PIN, 1U);

	return BSP_INIT_SUCCESS;
}

void Bsp_Deinit(void)
{
	/* De-Initialize FlexCAN driver */

	return;
}

uint32_t Bsp_GetCpuClockHz(void)
{
    return (uint32_t)Clock_Ip_GetClockFrequency(CORE_CLK);
}

